name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_TAG: dev
      DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/desec-ddns

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker Tag for Release
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          platforms: linux/amd64,linux/arm64
